name: ParticleAPI
version: '${version}'
main: net.gerasiov.particleapi.ParticleAPI
api-version: 1.19
authors: [ gerasiov ]
description: gerasiov's API for easier development of effects that use particles.
